### ISSUE TITLE
check_for_static_data() does not handle HTTP errors appropriately

### ISSUE THREAD

**Issue by seanblanchfield** [seanblanchfield/tfi-gtfs#1]
A `HTTP 502` "bad gateway" error was not caught appropriately in the `check_for_static_data()` function. This appears to have crashed the thread responsible for running scheduled jobs like checking for new downloads and for new live info. This has the effect of stopping live information from being incorporated into the results returned from the feed. These errors should be handled gracefully, with the thread retrying on an exponential back off (as is currently done with the live feed). 

```
Traceback (most recent call last):
  File "/usr/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.11/threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
  File "/app/server.py", line 209, in refresh
    if check_for_new_static_data():
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/gtfs.py", line 508, in check_for_new_static_data
    with urllib.request.urlopen(
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/urllib/request.py", line 525, in open
    response = meth(req, response)
               ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/urllib/request.py", line 634, in http_response
    response = self.parent.error(
               ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/urllib/request.py", line 563, in error
    return self._call_chain(*args)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/urllib/request.py", line 496, in _call_chain
    result = func(*args)
             ^^^^^^^^^^^
  File "/usr/lib/python3.11/urllib/request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 502: Bad Gateway
```

**Comment by seanblanchfield** [comment]
Closed with [21d7486](https://github.com/seanblanchfield/tfi-gtfs/commit/21d74865ef1d2861a41b84f978472a939629ce99).
